Yusuf_Aydın_Tutoring_MVC/Tutoring/Tutoring/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Tutoring.Business.Abstract;
using Tutoring.Entity.Concrete;
using Tutoring.Entity.Concrete.ComplexTypes;
using Tutoring.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;



namespace Tutoring.MVC.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class CartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartManager;
        private readonly ICartItemService _cartItemManager;
        private readonly IOrderService _orderManager;
        private readonly INotyfService _notyf;

        public CartController(UserManager<User> userManager, ICartService cartManager, INotyfService notyf, ICartItemService cartItemManager, IOrderService orderManager)
        {
            _userManager = userManager;
            _cartManager = cartManager;
            _notyf = notyf;
            _cartItemManager = cartItemManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartManager.GetCartByUserId(userId);
            CartViewModel model = new CartViewModel
            {
                CartId = cart.Id,
                CartItems = cart.CartItems
                    .Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        LessonId = ci.Lesson.Id,
                        LessonName = ci.Lesson.Name,
                        LessonUrl = ci.Lesson.Url,
                        LessonImageUrl = ci.Lesson.ImageUrl,
                        Price = ci.Lesson.Price,
                        Amount = ci.Amount
                    }).ToList()
            };
            return View(model);
        }
        public async Task<IActionResult> AddToCart(int id, int amount)
        {
            var userId = _userManager.GetUserId(User);
            await _cartManager.AddToCart(userId, id, amount);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeAmount(int cartItemId, int amount)
        {
            if (ModelState.IsValid)
            {
                await _cartItemManager.ChangeAmountAsync(cartItemId, amount);
            }
            else
            {
                _notyf.Warning("Lütfen adedi boş bırakmayınız");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteItemFromCart(int id)
        {
            var cartItem = await _cartItemManager.GetByIdAsync(id);
            _cartItemManager.Delete(cartItem);
            _notyf.Success("Kitap sepetinizden silindi");
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart(int id)
        {
            _cartItemManager.ClearCart(id);
            _notyf.Success("Sepetiniz boşaltılmıştır.");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            string userId = _userManager.GetUserId(User);
            User user = await _userManager.FindByIdAsync(userId);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            OrderViewModel model = new OrderViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                City = user.City,
                PhoneNumber = user.PhoneNumber,
                Email = user.Email,
                Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                         LessonId = ci.LessonId,
                        LessonName = ci.Lesson.Name,
                        Price = ci.Lesson.Price,
                        Amount = ci.Amount,
                        LessonImageUrl = ci.Lesson.ImageUrl
                    }).ToList()
                },
                CardName = "Alex de Souza",
                CardNumber = "5890040000000016",
                ExpirationYear = "2028",
                ExpirationMonth = "10",
                Cvc = "123"
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            string userId = _userManager.GetUserId(User);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            if (ModelState.IsValid)
            {
                model.Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        LessonId = ci.LessonId,
                        LessonName = ci.Lesson.Name,
                        Price = ci.Lesson.Price,
                        LessonImageUrl = ci.Lesson.ImageUrl,
                        Amount = ci.Amount
                    }).ToList()
                };
                Payment payment = PaymentProcess(model);
                if (payment.Status == "success")
                {
                    await SaveOrder(model, userId);
                    _cartItemManager.ClearCart(model.Cart.CartId);
                    _notyf.Success("Ödeme işlemi başarıyla tamamlanmıştır");
                    return RedirectToAction("Index", "Home");
                }
                _notyf.Error("Bir hata oluştu");
            }

            return View();
        }
        [NonAction]
        private Payment PaymentProcess(OrderViewModel model)
        {
            #region Options
            Options options = new Options();
            options.ApiKey = "sandbox-313Mg6w05g35vEZZXgG5dL5YW6LiUGJl";
            options.SecretKey = "sandbox-tkue5CZOz5usUARA3DmXPQAVnbJkcXx5";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            #endregion
            #region Request
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = "123456789";
            request.Price = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.PaidPrice = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.Cart.CartId.ToString();
            request.PaymentChannel = PaymentChannel.MOBILE_WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();
            #region PaymentCard
            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;
            #endregion
            #region Buyer
            Buyer buyer = new Buyer();
            buyer.Id = "12345";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.PhoneNumber;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = model.Address;
            buyer.Ip = "85.34.78.112";
            buyer.City = model.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;
            #endregion
            #region Addresses
            Address shippingAddress = new Address();
            shippingAddress.ContactName = model.FirstName + " " + model.LastName;
            shippingAddress.City = model.City;
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = model.Address;
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = model.FirstName + " " + model.LastName;
            billingAddress.City = model.City;
            billingAddress.Country = "Turkey";
            billingAddress.Description = model.Address;
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;
            #endregion
            #region Basket Items
            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.Cart.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.CartItemId.ToString();
                basketItem.Name = item.LessonName;
                basketItem.Category1 = "Kitap";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = Convert.ToInt32(item.Price * item.Amount).ToString();
                basketItems.Add(basketItem);
            }
            request.BasketItems = basketItems;
            #endregion
            #endregion
            Payment payment = Payment.Create(request, options);
            return payment;
        }
        [NonAction]
        private async Task SaveOrder(OrderViewModel model, string userId)
        {
            Order order = new Order();
            order.UserId = userId;

Yusuf_Aydın_Tutoring_MVC/Tutoring/Tutoring/Controllers/TutoringController.cs
using Tutoring.Business.Abstract;
using Tutoring.Business.Concrete;
using Tutoring.Entity.Concrete;
using Tutoring.Models;
using Microsoft.AspNetCore.Mvc;

namespace Tutoring.MVC.Controllers
{
    public class TutoringController : Controller
    {
        private readonly ILessonService _lessonManager;
        private readonly ITeacherService _teacherManager;

        public TutoringController(ILessonService lessonManager, ITeacherService teacherManager)
        {
            _lessonManager = lessonManager;
            _teacherManager = teacherManager;
        }

        public async Task<IActionResult> LessonList(string categoryurl = null, string teacherurl = null)
        {
            List<Lesson> lessonList = await _lessonManager.GetAllActiveLessonsAsync(categoryurl, teacherurl);
            List<LessonViewModel> lessonViewModelList = lessonList.Select(p => new LessonViewModel
            {
                Id = p.Id,
                Name = p.Name,
                Price = p.Price,
                Url = p.Url,
                ImageUrl = p.ImageUrl,
                TeacherName = p.Teacher.FirstName + " " + p.Teacher.LastName,
                TeacherUrl = p.Teacher.Url,
            }).ToList();
            return View(lessonViewModelList);
        }
        public async Task<IActionResult> LessonDetails(string url)
        {
            Lesson lesson = await _lessonManager.GetLessonByUrlAsync(url);
            LessonDetailsViewModel lessonDetailsViewModel = new LessonDetailsViewModel
            {
                Id = lesson.Id,
                Name = lesson.Name,
                TeacherName = lesson.Teacher.FirstName + " " + lesson.Teacher.LastName,
                TeacherAbout = lesson.Teacher.About,
                TeacherUrl = lesson.Teacher.Url,
                Url = lesson.Url,
                ImageUrl = lesson.ImageUrl,
                Description = lesson.Description,
                Price = lesson.Price,
                Categories = lesson.LessonCategories.Select(bc => new CategoryViewModel
                {
                    Name = bc.Category.Name,
                    Url = bc.Category.Url
                }).ToList()
            };
            return View(lessonDetailsViewModel);
        }
        public async Task<IActionResult> TeacherList(string categoryurl = null, string teacherurl = null)
        {
            List<Teacher> teacherList = await _teacherManager.GetAllActiveTeachersAsync(categoryurl, teacherurl);
            List<TeacherViewModel> teacherViewModelList = teacherList.Select(p => new TeacherViewModel
            {
                Id = p.Id,
                Name = p.FirstName + " " + p.LastName,
                Url = p.Url,
                ImageUrl = p.PhotoUrl
            }).ToList();
            return View(teacherViewModelList);
        }
        public async Task<IActionResult> TeacherDetails(string url)
        {
            Teacher teacher = await _teacherManager.GetTeachersByUrlAsync(url);
            TeacherDetailsViewModel teacherDetailsViewModel = new TeacherDetailsViewModel
            {
                Id = teacher.Id,
                TeacherName = teacher.FirstName + " " + teacher.LastName,
                TeacherAbout = teacher.About,
                TeacherUrl = teacher.Url,
                Url = teacher.Url,
                ImageUrl = teacher.PhotoUrl
            };
            return View(teacherDetailsViewModel);
        }
    }
}

Yusuf_Aydın_Tutoring_MVC/Tutoring/Tutoring/Views/Shared/MenuPartial.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
    </li>
</ul>

<ul class="navbar-nav text-end">
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area="Admin"
               asp-controller="Home"
               asp-action="Index">Admin</a>
        </li>
    }

    @if (User.Identity.IsAuthenticated)
    {
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area=""
               asp-controller="Account"
               asp-action="MyAccount"
               asp-route-id="@User.Identity.Name">
                @User.Identity.Name
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area=""
               asp-controller="Cart"
               asp-action="Index">
                <i class="fa fa-shopping-cart text-danger fs-3"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area=""
               asp-controller="Account"
               asp-action="Logout">
                Çıkış Yap
            </a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area=""
               asp-controller="Account"
               asp-action="Login">
                Giriş Yap
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark"
               asp-area=""
               asp-controller="Account"
               asp-action="Register">
                Kayıt Ol
            </a>
        </li>
    }
</ul>

Yusuf_Aydın_Tutoring_MVC/Tutoring/Tutoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tutoring</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tutoring.styles.css" asp-append-version="true" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tutoring.MVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                @await Html.PartialAsync("_MenuPartial")
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Tutoring</h1>
                <p class="lead fw-normal text-white-50 mb-0">Hoş Geldiniz</p>
            </div>
        </div>
    </header>
    <br />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="py-5 m-0 bg-dark">
        <div class="container">
            <p class="mt-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Yusuf_Aydın_Tutoring_MVC/Tutoring/Tutoring/Views/Shared/_LessonPartial.cshtml
@model LessonViewModel
<div class="card h-100" style="width:350px; height:200px">
	<!-- Sale badge-->
	<div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
	<!-- Lesson image-->
	<a asp-area="" asp-controller="Tutoring" asp-action="LessonDetails" asp-route-url="@Model.Url">
		<img src="~/images/lessons/1.jpg" class="card-img-top" style="width:348px; height:200px" />
	</a>
	</a>
	<!-- Lesson details-->
	<div class="card-body">
		<div class="text-center">
			<!-- Product name-->
			<h5 class="card-title">@Model.Name</h5>
			<h4>@($"{Model.Price:C0}")</h4>
		</div>
	</div>
	<!-- Lesson actions-->
	<div class="d-flex justify-content-center m-1">
		<form asp-area="" asp-controller="Cart" asp-action="AddToCart" method="post">
			<input type="hidden" asp-for="Id" />
			<button type="submit" class="btn btn-outline-dark">Sepete Ekle</button>
			<input class="form-control d-inline" style="width:60px;" type="number" name="amount" min="1" max="9"
				value="1" />
		</form>
	</div>
</div>